#!/usr/bin/env python3
"""DPO/ORPO training on preference pairs generated by rejection sampling.

Phase C of the Student-Teacher-Validator pipeline:
    Takes DPO pairs (chosen/rejected) and trains the student model
    to prefer correct, validated responses over incorrect ones.

Usage:
    python train_dpo.py stm32 \
        --model ./runs/tuning-party-hf_stm32/train_output/adapter \
        --dpo-dataset ./dpo_pairs/stm32/dpo_stm32_20260309.jsonl \
        --method dpo

    python train_dpo.py spice --method orpo  # ORPO: no ref model needed
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent

DOMAINS = [
    "stm32", "spice", "iot", "power", "dsp", "emc",
    "kicad", "embedded", "platformio", "freecad",
]


def load_dpo_dataset(path: str):
    """Load DPO pairs from JSONL."""
    from datasets import Dataset

    rows = []
    with open(path) as f:
        for line in f:
            row = json.loads(line)
            # Flatten conversational format to text for DPO
            prompt_msgs = row.get("prompt", [])
            chosen_msgs = row.get("chosen", [])
            rejected_msgs = row.get("rejected", [])
            rows.append({
                "prompt": prompt_msgs,
                "chosen": chosen_msgs,
                "rejected": rejected_msgs,
            })

    return Dataset.from_list(rows)


def train_dpo(
    model_path: str,
    dataset_path: str,
    domain: str,
    output_dir: str,
    method: str = "dpo",
    beta: float = 0.1,
    learning_rate: float = 5e-7,
    epochs: int = 1,
    batch_size: int = 2,
    max_length: int = 1024,
    lora_r: int = 16,
    lora_alpha: int = 32,
):
    """Run DPO or ORPO training."""
    import torch
    from peft import LoraConfig
    from transformers import AutoTokenizer

    print(f"Loading dataset from {dataset_path}...")
    dataset = load_dpo_dataset(dataset_path)
    print(f"  {len(dataset)} preference pairs")

    if len(dataset) < 10:
        print("ERROR: Need at least 10 DPO pairs for meaningful training")
        return False

    # Split train/eval
    split = dataset.train_test_split(test_size=0.1, seed=42)
    train_dataset = split["train"]
    eval_dataset = split["test"]
    print(f"  Train: {len(train_dataset)}, Eval: {len(eval_dataset)}")

    peft_config = LoraConfig(
        r=lora_r,
        lora_alpha=lora_alpha,
        target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],
        lora_dropout=0.05,
        bias="none",
        task_type="CAUSAL_LM",
    )

    if method == "dpo":
        from trl import DPOTrainer, DPOConfig

        training_args = DPOConfig(
            output_dir=output_dir,
            beta=beta,
            learning_rate=learning_rate,
            num_train_epochs=epochs,
            per_device_train_batch_size=batch_size,
            per_device_eval_batch_size=batch_size,
            gradient_accumulation_steps=8,
            gradient_checkpointing=True,
            bf16=torch.cuda.is_available(),
            logging_steps=10,
            eval_strategy="steps",
            eval_steps=50,
            save_steps=100,
            save_total_limit=2,
            max_length=max_length,
            report_to="none",
        )

        print(f"\nInitializing DPO trainer (beta={beta}, lr={learning_rate})...")
        trainer = DPOTrainer(
            model=model_path,
            ref_model=None,  # Auto-reference from initial state
            args=training_args,
            train_dataset=train_dataset,
            eval_dataset=eval_dataset,
            peft_config=peft_config,
        )

    elif method == "orpo":
        try:
            from trl.experimental.orpo import ORPOTrainer, ORPOConfig
        except ImportError:
            from trl import ORPOTrainer, ORPOConfig

        training_args = ORPOConfig(
            output_dir=output_dir,
            beta=beta,
            learning_rate=learning_rate,
            num_train_epochs=epochs,
            per_device_train_batch_size=batch_size,
            per_device_eval_batch_size=batch_size,
            gradient_accumulation_steps=8,
            gradient_checkpointing=True,
            bf16=torch.cuda.is_available(),
            logging_steps=10,
            eval_strategy="steps",
            eval_steps=50,
            save_steps=100,
            save_total_limit=2,
            max_length=max_length,
            report_to="none",
        )

        print(f"\nInitializing ORPO trainer (beta={beta}, lr={learning_rate})...")
        print("  (no reference model needed — saves ~50% VRAM)")
        trainer = ORPOTrainer(
            model=model_path,
            args=training_args,
            train_dataset=train_dataset,
            eval_dataset=eval_dataset,
            peft_config=peft_config,
        )
    else:
        print(f"Unknown method: {method}")
        return False

    # Train
    print(f"\nTraining ({method.upper()})...")
    train_result = trainer.train()

    # Save
    trainer.save_model(os.path.join(output_dir, "final"))
    print(f"\nModel saved to {output_dir}/final")
    print(f"Training metrics: {train_result.metrics}")

    # Save training info
    info = {
        "domain": domain,
        "method": method,
        "model": model_path,
        "dpo_pairs": len(dataset),
        "beta": beta,
        "learning_rate": learning_rate,
        "epochs": epochs,
        "lora_r": lora_r,
        "lora_alpha": lora_alpha,
        "train_loss": train_result.metrics.get("train_loss"),
        "eval_loss": train_result.metrics.get("eval_loss"),
    }
    with open(os.path.join(output_dir, "training_info.json"), "w") as f:
        json.dump(info, f, indent=2)

    return True


def main() -> int:
    parser = argparse.ArgumentParser(description="DPO/ORPO training on preference pairs")
    parser.add_argument("domain", choices=DOMAINS)
    parser.add_argument("--model", required=True, help="Base model or SFT adapter path")
    parser.add_argument("--dpo-dataset", required=True, help="DPO pairs JSONL file")
    parser.add_argument("--output-dir", default=None)
    parser.add_argument("--method", choices=["dpo", "orpo"], default="dpo")
    parser.add_argument("--beta", type=float, default=0.1)
    parser.add_argument("--learning-rate", type=float, default=5e-7)
    parser.add_argument("--epochs", type=int, default=1)
    parser.add_argument("--batch-size", type=int, default=2)
    parser.add_argument("--max-length", type=int, default=1024)
    parser.add_argument("--lora-r", type=int, default=16)
    parser.add_argument("--lora-alpha", type=int, default=32)
    args = parser.parse_args()

    output_dir = args.output_dir or str(
        SCRIPT_DIR / "runs" / f"{args.method}_{args.domain}_{time.strftime('%Y%m%d_%H%M%S')}"
    )

    print("=" * 60)
    print(f"{args.method.upper()} Training — {args.domain}")
    print(f"Model:    {args.model}")
    print(f"Dataset:  {args.dpo_dataset}")
    print(f"Method:   {args.method} (beta={args.beta})")
    print(f"Output:   {output_dir}")
    print("=" * 60)

    success = train_dpo(
        model_path=args.model,
        dataset_path=args.dpo_dataset,
        domain=args.domain,
        output_dir=output_dir,
        method=args.method,
        beta=args.beta,
        learning_rate=args.learning_rate,
        epochs=args.epochs,
        batch_size=args.batch_size,
        max_length=args.max_length,
        lora_r=args.lora_r,
        lora_alpha=args.lora_alpha,
    )

    return 0 if success else 1


if __name__ == "__main__":
    raise SystemExit(main())
