"""Extract quality code from cloned repos and convert to training datasets.

For each source:
1. Find relevant code files (.c, .h, .py, .rs, .spice, .sch)
2. Extract with context (README, comments, file path as metadata)
3. Quality filter: min length, has real code, not auto-generated
4. Convert to conversations format with contextual Q&A
5. Dedup against existing datasets
"""

import json
import os
import hashlib

SOURCES_DIR = "finetune/sources"
OUTPUT_DIR = "finetune/datasets/quality_sources"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Existing hashes for cross-dedup
existing_hashes = set()
for d in ["finetune/datasets", "finetune/datasets/cleaned_final", "finetune/datasets/hf_imports"]:
    if not os.path.isdir(d):
        continue
    for fn in os.listdir(d):
        if not fn.endswith(".jsonl"):
            continue
        try:
            with open(os.path.join(d, fn)) as f:
                for line in f:
                    if line.strip():
                        h = hashlib.md5(line.strip()[:500].encode()).hexdigest()
                        existing_hashes.add(h)
        except:
            pass

print(f"Loaded {len(existing_hashes)} existing hashes for cross-dedup")


def read_file_safe(path, max_size=50000):
    try:
        with open(path, "r", errors="replace") as f:
            return f.read(max_size)
    except:
        return ""


def find_readme(directory):
    """Find README in directory or parent."""
    for name in ["README.md", "README.rst", "README.txt", "README"]:
        p = os.path.join(directory, name)
        if os.path.exists(p):
            return read_file_safe(p, 2000)
    return ""


def is_autogenerated(content):
    """Detect auto-generated files."""
    markers = ["DO NOT EDIT", "AUTO-GENERATED", "This file is generated", "Generated by", "machine-generated"]
    first_lines = content[:500].lower()
    return any(m.lower() in first_lines for m in markers)


def extract_esp_idf():
    """Extract ESP-IDF examples as Q&A pairs."""
    base = os.path.join(SOURCES_DIR, "esp-idf-examples", "examples")
    if not os.path.isdir(base):
        print("ESP-IDF not found"); return []

    results = []
    for root, dirs, files in os.walk(base):
        # Find main source file
        main_c = None
        for f in files:
            if f in ("main.c", "app_main.c") or (f.endswith(".c") and "main" in f):
                main_c = os.path.join(root, f)
                break
        if not main_c:
            continue

        code = read_file_safe(main_c)
        if len(code) < 100 or is_autogenerated(code):
            continue

        # Get context
        readme = find_readme(root) or find_readme(os.path.dirname(root))
        rel_path = os.path.relpath(root, base)
        rel_path.split(os.sep)[0] if os.sep in rel_path else rel_path

        # Build Q&A
        question = f"Write an ESP-IDF example for: {rel_path.replace(os.sep, ' / ')}"
        if readme:
            question += f"\n\nContext from README:\n{readme[:500]}"

        answer = f"Here is the ESP-IDF implementation ({rel_path}):\n\n```c\n{code[:3000]}\n```"

        results.append({
            "conversations": [
                {"from": "system", "value": "You are an expert ESP-IDF developer. You write production-grade ESP32 firmware."},
                {"from": "human", "value": question},
                {"from": "gpt", "value": answer},
            ],
            "domain": "esp-idf",
            "source": "espressif/esp-idf",
            "license": "Apache-2.0",
            "path": rel_path,
        })

    return results


def extract_pico():
    """Extract Pico examples."""
    base = os.path.join(SOURCES_DIR, "pico-examples")
    if not os.path.isdir(base):
        print("pico-examples not found"); return []

    results = []
    for root, dirs, files in os.walk(base):
        for f in files:
            if not f.endswith(".c"):
                continue
            path = os.path.join(root, f)
            code = read_file_safe(path)
            if len(code) < 100 or is_autogenerated(code):
                continue

            rel = os.path.relpath(path, base)
            rel.split(os.sep)[0]
            readme = find_readme(root)

            question = f"Write a Raspberry Pi Pico (RP2040) example for: {rel.replace(os.sep, ' / ')}"
            if readme:
                question += f"\n\nDescription:\n{readme[:400]}"

            answer = f"```c\n{code[:3000]}\n```"

            results.append({
                "conversations": [
                    {"from": "system", "value": "You are an expert RP2040/Pico SDK developer."},
                    {"from": "human", "value": question},
                    {"from": "gpt", "value": answer},
                ],
                "domain": "rp2040",
                "source": "raspberrypi/pico-examples",
                "license": "BSD-3-Clause",
            })
    return results


def extract_cmsis_dsp():
    """Extract CMSIS-DSP examples and source."""
    base = os.path.join(SOURCES_DIR, "CMSIS-DSP")
    if not os.path.isdir(base):
        print("CMSIS-DSP not found"); return []

    results = []
    for subdir in ["Source", "Examples"]:
        src_dir = os.path.join(base, subdir)
        if not os.path.isdir(src_dir):
            continue
        for root, dirs, files in os.walk(src_dir):
            for f in files:
                if not (f.endswith(".c") or f.endswith(".h")):
                    continue
                path = os.path.join(root, f)
                code = read_file_safe(path)
                if len(code) < 100 or is_autogenerated(code):
                    continue

                rel = os.path.relpath(path, base)
                func_name = os.path.splitext(f)[0]

                question = f"Show the CMSIS-DSP implementation of {func_name} ({rel})"
                answer = f"CMSIS-DSP {func_name}:\n\n```c\n{code[:3000]}\n```"

                results.append({
                    "conversations": [
                        {"from": "system", "value": "You are an expert in ARM CMSIS-DSP optimized signal processing."},
                        {"from": "human", "value": question},
                        {"from": "gpt", "value": answer},
                    ],
                    "domain": "dsp",
                    "source": "ARM-software/CMSIS-DSP",
                    "license": "Apache-2.0",
                })
    return results


def extract_ch32fun():
    """Extract ch32fun RISC-V examples."""
    base = os.path.join(SOURCES_DIR, "ch32fun")
    if not os.path.isdir(base):
        print("ch32fun not found"); return []

    results = []
    for root, dirs, files in os.walk(base):
        for f in files:
            if not f.endswith(".c"):
                continue
            path = os.path.join(root, f)
            code = read_file_safe(path)
            if len(code) < 100 or is_autogenerated(code):
                continue

            rel = os.path.relpath(path, base)
            if "examples" not in rel.lower() and "fun" not in rel.lower():
                continue

            question = f"Write a CH32V RISC-V bare-metal example: {rel.replace(os.sep, ' / ')}"
            answer = f"CH32V bare-metal ({rel}):\n\n```c\n{code[:3000]}\n```"

            results.append({
                "conversations": [
                    {"from": "system", "value": "You are an expert in RISC-V bare-metal programming for WCH CH32V microcontrollers."},
                    {"from": "human", "value": question},
                    {"from": "gpt", "value": answer},
                ],
                "domain": "riscv",
                "source": "cnlohr/ch32fun",
                "license": "MIT",
            })
    return results


def extract_spice():
    """Extract SPICE netlists."""
    base = os.path.join(SOURCES_DIR, "spice-datasets")
    if not os.path.isdir(base):
        print("spice-datasets not found"); return []

    results = []
    for root, dirs, files in os.walk(base):
        for f in files:
            if not (f.endswith(".spice") or f.endswith(".cir") or f.endswith(".net") or f.endswith(".sp")):
                continue
            path = os.path.join(root, f)
            code = read_file_safe(path)
            if len(code) < 50:
                continue

            rel = os.path.relpath(path, base)
            name = os.path.splitext(f)[0]

            question = f"Show a SPICE netlist for: {name} ({rel})"
            answer = f"SPICE netlist ({name}):\n\n```spice\n{code[:3000]}\n```"

            results.append({
                "conversations": [
                    {"from": "system", "value": "You are an expert SPICE simulation engineer."},
                    {"from": "human", "value": question},
                    {"from": "gpt", "value": answer},
                ],
                "domain": "spice",
                "source": "symbench/spice-datasets",
                "license": "GPL-3.0",
            })
    return results


def extract_liquid_dsp():
    """Extract liquid-dsp examples."""
    base = os.path.join(SOURCES_DIR, "liquid-dsp")
    if not os.path.isdir(base):
        print("liquid-dsp not found"); return []

    results = []
    for subdir in ["examples", "src"]:
        src = os.path.join(base, subdir)
        if not os.path.isdir(src):
            continue
        for root, dirs, files in os.walk(src):
            for f in files:
                if not f.endswith(".c"):
                    continue
                path = os.path.join(root, f)
                code = read_file_safe(path)
                if len(code) < 100 or is_autogenerated(code):
                    continue

                os.path.relpath(path, base)
                name = os.path.splitext(f)[0]

                question = f"Show the liquid-dsp implementation of {name}"
                answer = f"liquid-dsp {name}:\n\n```c\n{code[:3000]}\n```"

                results.append({
                    "conversations": [
                        {"from": "system", "value": "You are an expert in software-defined radio and DSP programming."},
                        {"from": "human", "value": question},
                        {"from": "gpt", "value": answer},
                    ],
                    "domain": "dsp",
                    "source": "jgaeddert/liquid-dsp",
                    "license": "MIT",
                })
    return results


def extract_ngspice():
    """Extract ngspice examples."""
    base = os.path.join(SOURCES_DIR, "ngspice")
    if not os.path.isdir(base):
        print("ngspice not found"); return []

    results = []
    for root, dirs, files in os.walk(base):
        for f in files:
            if not (f.endswith(".cir") or f.endswith(".sp") or f.endswith(".spice")):
                continue
            path = os.path.join(root, f)
            code = read_file_safe(path)
            if len(code) < 50:
                continue

            os.path.relpath(path, base)
            name = os.path.splitext(f)[0]

            question = f"Show an ngspice simulation example: {name}"
            answer = f"ngspice example ({name}):\n\n```spice\n{code[:3000]}\n```"

            results.append({
                "conversations": [
                    {"from": "system", "value": "You are an expert ngspice simulation engineer."},
                    {"from": "human", "value": question},
                    {"from": "gpt", "value": answer},
                ],
                "domain": "spice",
                "source": "ngspice",
                "license": "BSD-3-Clause",
            })
    return results


# Run all extractors
extractors = [
    ("esp-idf", extract_esp_idf),
    ("pico", extract_pico),
    ("cmsis-dsp", extract_cmsis_dsp),
    ("ch32fun", extract_ch32fun),
    ("spice-datasets", extract_spice),
    ("liquid-dsp", extract_liquid_dsp),
    ("ngspice", extract_ngspice),
]

grand_total = 0
for name, fn in extractors:
    print(f"\n=== Extracting: {name} ===")
    results = fn()

    # Dedup against existing
    deduped = []
    dupes = 0
    for r in results:
        text = " ".join(c.get("value", "") for c in r["conversations"])
        h = hashlib.md5(text[:500].encode()).hexdigest()
        if h in existing_hashes:
            dupes += 1
            continue
        existing_hashes.add(h)
        deduped.append(r)

    # Quality filter
    quality = []
    for r in deduped:
        answer = " ".join(c.get("value", "") for c in r["conversations"] if c.get("from") in ("gpt", "assistant"))
        if len(answer) < 100:
            continue
        quality.append(r)

    # Save
    output = os.path.join(OUTPUT_DIR, f"{name}_quality.jsonl")
    with open(output, "w") as f:
        for r in quality:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")

    print(f"  Extracted: {len(results)}, Deduped: {dupes}, Quality filtered: {len(deduped)-len(quality)}, FINAL: {len(quality)}")
    grand_total += len(quality)

# Summary
print(f"\n{'='*60}")
print(f"TOTAL QUALITY EXAMPLES: {grand_total}")
print(f"{'='*60}")
for fn in sorted(os.listdir(OUTPUT_DIR)):
    if fn.endswith(".jsonl"):
        lines = sum(1 for _ in open(os.path.join(OUTPUT_DIR, fn)))
        print(f"  {fn}: {lines}")
