use_default_settings: true

general:
  instance_name: "Mascarade Search"
  debug: false

search:
  safe_search: 0
  autocomplete: "google"
  default_lang: "fr"

server:
  secret_key: "ultrasecretkey"  # overridden by env SEARXNG_SECRET
  bind_address: "0.0.0.0"
  port: 8080
  image_proxy: true

ui:
  static_use_hash: true
  default_theme: simple
  theme_args:
    simple_style: dark

engines:
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false

  - name: google
    engine: google
    shortcut: g
    disabled: false

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    disabled: false

  - name: github
    engine: github
    shortcut: gh
    disabled: false

  - name: arxiv
    engine: arxiv
    shortcut: arx
    disabled: false
